# Default to SQLite locally, Postgres in production.
# Fly.io sets DATABASE_URL for Postgres.

sqlite: &sqlite
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *sqlite
  database: storage/development.sqlite3

test:
  <<: *sqlite
  database: storage/test.sqlite3

production:
  primary:
    <<: *postgres
  cache:
    <<: *postgres
    migrations_paths: db/cache_migrate
  queue:
    <<: *postgres
    migrations_paths: db/queue_migrate
